public class Demo50 {
    public selectoption[] MyOptions{get;set;}
    public demo50(){
        selectoption OP1=new selectoption('null','none');
        selectoption OP2=new selectoption('one','jan');
         selectoption OP3=new selectoption('two','feb');
         selectoption OP4=new selectoption('three','march');
         selectoption OP5=new selectoption('four','april');
         selectoption OP6=new selectoption('five','may');
         selectoption OP7=new selectoption('six','june');
         selectoption OP8=new selectoption('seven','july');
         selectoption OP9=new selectoption('eight','august');
         selectoption OP10=new selectoption('nine','sept');
         selectoption OP11=new selectoption('ten','oct');
         selectoption OP12=new selectoption('eleven','nov');
         selectoption OP13=new selectoption('twelve','dec');
        Myoptions=new selectoption[]{OP1,OP2,OP3,OP4,OP5,OP6,OP7,OP8,OP9,OP10,OP11,OP12,OP13};
        
        
}
    }